DEFAULT_MAX_COMMITMENT_LOOKBACK = 360
DEFAULT_CHAIN_SYNC_INTERVAL = 30
MAX_WORKERS = 4
HEARTBEAT_INTERVAL = 30

#  Yield control every N blocks to prevent blocking WebSocket connections
CHAIN_SCAN_YIELD_INTERVAL = 2

# API Pagination constants
DEFAULT_PAGE_LIMIT = 100
MAX_PAGE_LIMIT = 1000
MIN_PAGE_LIMIT = 1

BACKEND_PORT = 8080
